version: '4.17'
services:
  test-db:
    image: postgres:alpine3.17
    ports:
      - 5435:5432
    networks:
      - APINetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123pswd
      POSTGRES_DB: getfitgo_test
  dev-db:
    image: postgres:alpine3.17
    ports:
      - 5434:5432
    networks:
      - APINetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123pswd
      POSTGRES_DB: getfitgo_dev
